import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:amazcart/model/NewModel/Order/OrderListModel.dart';

void main() {
  const jsonString = '''
{
    "orders": [
        {
            "id": 331,
            "customer_id": 159,
            "order_payment_id": 673,
            "order_type": null,
            "order_number": "20260618000257",
            "payment_type": 1,
            "is_paid": 0,
            "is_confirmed": 0,
            "is_completed": 0,
            "is_cancelled": 0,
            "cancel_reason_id": null,
            "customer_email": "no-email@checkout.com",
            "customer_phone": "9845614044",
            "customer_shipping_address": 121,
            "customer_billing_address": 121,
            "number_of_package": 1,
            "grand_total": 4800,
            "sub_total": 4800,
            "discount_total": 0,
            "shipping_total": 0,
            "number_of_item": 3,
            "order_status": "0",
            "tax_amount": 0,
            "note": null,
            "delivery_type": "home_delivery",
            "pickup_location_id": null,
            "created_at": "2026-06-18T04:16:59.000000Z",
            "updated_at": "2026-06-18T04:16:59.000000Z",
            "is_received": 0,
            "customer": {
                "id": 159,
                "first_name": "madhu",
                "last_name": "madhu",
                "username": "9845614044",
                "photo": null,
                "role_id": 4,
                "mobile_verified_at": null,
                "email": null,
                "is_verified": 0,
                "verify_code": null,
                "email_verified_at": null,
                "notification_preference": "mail",
                "is_active": 1,
                "avatar": null,
                "slug": null,
                "phone": "7760596879",
                "date_of_birth": null,
                "description": null,
                "secret_login": 0,
                "lang_code": "en",
                "currency_id": 47,
                "currency_code": "INR",
                "created_at": "2026-05-27T08:08:46.000000Z",
                "updated_at": "2026-06-18T04:13:59.000000Z",
                "others": null,
                "name": "madhu madhu"
            },
            "salesman": {
                "id": 3,
                "name": "Harish",
                "phone_number": "9611119365"
            },
            "packages": [
                {
                    "id": 329,
                    "order_id": 331,
                    "carrier_order_id": null,
                    "seller_id": 18,
                    "package_code": "26061809594615",
                    "number_of_product": 1,
                    "shipping_cost": 0,
                    "shipping_date": "Est. Arrival Date: Jun 18-Jun 21",
                    "shipping_method": 3,
                    "carrier_id": "4",
                    "shipped_by": null,
                    "is_cancelled": 0,
                    "is_paid": 0,
                    "cancel_reason_id": null,
                    "is_reviewed": 0,
                    "delivery_status": "1",
                    "last_updated_by": null,
                    "gst_claimed": 0,
                    "tax_amount": 0,
                    "created_at": "2026-06-18T04:16:59.000000Z",
                    "updated_at": "2026-06-18T04:16:59.000000Z",
                    "carrier_response": null,
                    "pickup_point_id": 1,
                    "weight": 26,
                    "length": 0,
                    "breadth": 0,
                    "height": 0,
                    "deliveryStateName": "Pending",
                    "totalGST": 0,
                    "processes": [
                        {
                            "id": 1,
                            "name": "Pending",
                            "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s,",
                            "created_at": "2021-02-10T23:03:37.000000Z",
                            "updated_at": "2021-02-10T23:03:37.000000Z",
                            "translateName": "Pending",
                            "TranslateDescription": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s,"
                        },
                        {
                            "id": 2,
                            "name": "Processing",
                            "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s,",
                            "created_at": "2021-02-10T23:03:55.000000Z",
                            "updated_at": "2021-02-10T23:03:55.000000Z",
                            "translateName": "Processing",
                            "TranslateDescription": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s,"
                        },
                        {
                            "id": 3,
                            "name": "Shipped",
                            "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s,",
                            "created_at": "2021-02-10T23:04:08.000000Z",
                            "updated_at": "2021-02-10T23:04:08.000000Z",
                            "translateName": "Shipped",
                            "TranslateDescription": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s,"
                        },
                        {
                            "id": 5,
                            "name": "Delivered",
                            "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s,",
                            "created_at": "2021-02-10T23:04:43.000000Z",
                            "updated_at": "2021-02-10T23:05:02.000000Z",
                            "translateName": "Delivered",
                            "TranslateDescription": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s,"
                        }
                    ],
                    "seller": {
                        "id": 18,
                        "salesman_id": null,
                        "short_code": "BOM",
                        "first_name": "Dhatri-Bommasandra",
                        "last_name": null,
                        "store_name": null,
                        "username": "9986922041",
                        "photo": null,
                        "role_id": 5,
                        "mobile_verified_at": null,
                        "email": "seller1@gmail.com",
                        "is_verified": 1,
                        "verify_code": "ea8d9d0e4c1ad7356b3063174a003979fb608a4d",
                        "email_verified_at": null,
                        "notification_preference": "mail",
                        "is_active": 1,
                        "avatar": null,
                        "slug": "seller-1-shop",
                        "phone": null,
                        "gst_number": null,
                        "date_of_birth": null,
                        "description": null,
                        "secret_login": 0,
                        "lang_code": "en",
                        "currency_id": 47,
                        "currency_code": "INR",
                        "created_at": "2026-02-19T10:52:54.000000Z",
                        "updated_at": "2026-05-07T16:33:35.000000Z",
                        "others": null,
                        "affiliate_request": null,
                        "accept_affiliate_request": null,
                        "document": null,
                        "store_image": null,
                        "warehouse_id": null,
                        "coordinates": null,
                        "is_deleted": 0,
                        "name": "Dhatri-Bommasandra "
                    },
                    "products": [
                        {
                            "id": 555,
                            "package_id": 329,
                            "type": "product",
                            "product_sku_id": 47,
                            "qty": 3,
                            "price": 1600,
                            "total_price": 4800,
                            "tax_amount": 0,
                            "created_at": "2026-06-18T04:16:59.000000Z",
                            "updated_at": "2026-06-18T04:16:59.000000Z",
                            "seller_product_sku": {
                                "id": 47,
                                "user_id": 18,
                                "product_id": 47,
                                "product_sku_id": "26",
                                "product_stock": 43,
                                "purchase_price": 0,
                                "selling_price": 1600,
                                "status": 1,
                                "created_at": "2026-04-21T14:53:08.000000Z",
                                "updated_at": "2026-06-18T04:16:59.000000Z",
                                "product_variations": [],
                                "product": {
                                    "id": 47,
                                    "user_id": 18,
                                    "product_id": 26,
                                    "tax": 0,
                                    "tax_type": 47,
                                    "discount": 0,
                                    "discount_type": 1,
                                    "discount_start_date": null,
                                    "discount_end_date": null,
                                    "product_name": "Dhatri Royal Bullet Sona steam Rice",
                                    "slug": "dhatri-royal-bullet-sona-steam-rice",
                                    "thum_img": "",
                                    "status": 1,
                                    "stock_manage": 1,
                                    "is_approved": 0,
                                    "min_sell_price": 1600,
                                    "max_sell_price": 1600,
                                    "total_sale": 762,
                                    "avg_rating": 0,
                                    "recent_view": "2026-05-29T22:48:54.000000Z",
                                    "subtitle_1": "",
                                    "subtitle_2": "",
                                    "variantDetails": [],
                                    "MaxSellingPrice": 1600,
                                    "hasDeal": null,
                                    "rating": 0,
                                    "hasDiscount": "no",
                                    "ProductType": "product",
                                    "flash_deal": null,
                                    "product": {
                                        "id": 26,
                                        "product_name": "Dhatri Royal Bullet Sona Steam Rice 26Kg",
                                        "product_type": 1,
                                        "variant_sku_prefix": null,
                                        "unit_type_id": "Bag",
                                        "brand_id": 18,
                                        "thumbnail_image_source": "uploads/images/07-04-2026/69d4f0413c9bc.jpeg",
                                        "media_ids": "41",
                                        "barcode_type": "C39",
                                        "model_number": null,
                                        "shipping_type": 0,
                                        "shipping_cost": 0,
                                        "discount_type": 1,
                                        "discount": 0,
                                        "tax_type": null,
                                        "gst_group_id": null,
                                        "tax_id": null,
                                        "tax": 0,
                                        "pdf": "",
                                        "video_provider": "youtube",
                                        "video_link": null,
                                        "description": "",
                                        "specification": "",
                                        "minimum_order_qty": 1,
                                        "max_order_qty": 999,
                                        "meta_title": "",
                                        "meta_description": "",
                                        "meta_image": "",
                                        "is_physical": 1,
                                        "is_approved": 1,
                                        "status": 1,
                                        "display_in_details": 1,
                                        "requested_by": 1,
                                        "created_by": 1,
                                        "slug": "dhatri-royal-bullet-sona-steam-rice-26kg",
                                        "updated_by": null,
                                        "stock_manage": "0",
                                        "subtitle_1": "",
                                        "subtitle_2": "",
                                        "created_at": "2026-04-07T17:23:37.000000Z",
                                        "updated_at": "2026-04-07T17:23:37.000000Z"
                                    },
                                    "wish_list": null,
                                    "skus": [
                                        {
                                            "id": 47,
                                            "user_id": 18,
                                            "product_id": 47,
                                            "product_sku_id": "26",
                                            "product_stock": 43,
                                            "purchase_price": 0,
                                            "selling_price": 1600,
                                            "status": 1,
                                            "in_app_purchase": "",
                                            "created_at": "2026-04-21T14:53:08.000000Z",
                                            "updated_at": "2026-06-18T04:16:59.000000Z",
                                            "product_variations": null
                                        }
                                    ],
                                    "reviews": []
                                }
                            },
                            "gift_card": null
                        }
                    ],
                    "gift_card": null
                }
            ],
            "address": {
                "id": 327,
                "order_id": 331,
                "customer_id": 159,
                "shipping_name": "MADHUSUDHAN RICE TRADERS",
                "shipping_email": "MADHU@GMAIL.COM",
                "shipping_phone": "9845614044",
                "shipping_address": "Murgesh palya thippasandra",
                "shipping_country_id": "101",
                "shipping_state_id": "17",
                "shipping_city_id": "1558",
                "shipping_postcode": "560017",
                "bill_to_same_address": 1,
                "billing_name": "MADHUSUDHAN RICE TRADERS",
                "billing_email": "MADHU@GMAIL.COM",
                "billing_phone": "9845614044",
                "billing_address": "Murgesh palya thippasandra",
                "billing_country_id": "101",
                "billing_state_id": "17",
                "billing_city_id": "1558",
                "billing_postcode": "560017",
                "created_at": "2026-06-18T04:16:59.000000Z",
                "updated_at": "2026-06-18T04:16:59.000000Z",
                "get_shipping_country": {
                    "id": 101,
                    "code": "IN",
                    "name": "India",
                    "phonecode": "91",
                    "flag": "/flags/flag-of-India.jpg",
                    "status": 1,
                    "created_at": null,
                    "updated_at": null,
                    "torod_country_id": null
                },
                "get_shipping_state": {
                    "id": 17,
                    "name": "Karnataka",
                    "country_id": 101,
                    "status": 1,
                    "created_at": null,
                    "updated_at": null,
                    "torod_country_id": null,
                    "torod_state_id": null
                },
                "get_shipping_city": {
                    "id": 1558,
                    "name": "Bengaluru",
                    "state_id": 17,
                    "status": 1,
                    "created_at": null,
                    "updated_at": null,
                    "torod_state_id": null,
                    "torod_city_id": null
                }
            },
            "shipping_address": {
                "id": 121,
                "customer_id": 159,
                "name": "MADHUSUDHAN RICE TRADERS",
                "email": "MADHU@GMAIL.COM",
                "phone": "9845614044",
                "address": "Murgesh palya thippasandra",
                "city": "1558",
                "state": "17",
                "country": "101",
                "postal_code": "560017",
                "is_shipping_default": 1,
                "is_billing_default": 1,
                "created_at": "2026-05-27T09:10:50.000000Z",
                "updated_at": "2026-05-27T09:10:50.000000Z",
                "is_updated": 0
            },
            "billing_address": {
                "id": 121,
                "customer_id": 159,
                "name": "MADHUSUDHAN RICE TRADERS",
                "email": "MADHU@GMAIL.COM",
                "phone": "9845614044",
                "address": "Murgesh palya thippasandra",
                "city": "1558",
                "state": "17",
                "country": "101",
                "postal_code": "560017",
                "is_shipping_default": 1,
                "is_billing_default": 1,
                "created_at": "2026-05-27T09:10:50.000000Z",
                "updated_at": "2026-05-27T09:10:50.000000Z",
                "is_updated": 0
            }
        }
    ],
    "message": "success"
}
  ''';

  try {
    print('Parsing json...');
    final decoded = json.decode(jsonString);
    final parsed = OrderListModel.fromJson(decoded);
    print('Successfully parsed OrderListModel!');
    print('Orders count: ${parsed.orders?.length}');
    if (parsed.orders != null && parsed.orders!.isNotEmpty) {
      final order = parsed.orders!.first;
      print('First order id: ${order.id}');
      print('Billing name: ${order.orderAddress?.billingName}');
      print('Billing state: ${order.orderAddress?.getBillingState?.name}');
      print('Billing city: ${order.orderAddress?.getBillingCity?.name}');
      print('Billing country: ${order.orderAddress?.getBillingCountry?.name}');
      print('Shipping state: ${order.orderAddress?.getShippingState?.name}');
    }
  } catch (e, stack) {
    print('Parsing failed with exception: $e');
    print(stack);
  }
}
